// Command openapigen projects the native API's OpenAPI contract from
// the Go source. The api package's route table ([api.Routes]) supplies
// the paths and per-operation auth metadata; the contract structs the
// table references supply components/schemas, with each field's GoDoc
// comment carried over as its property description. Because the spec
// is generated, it cannot drift from the code — the structs and the
// route table ARE the contract (issue #43).
//
// Run via `just generate` (a go:generate directive in the api package
// invokes it with the package directory as cwd). Output lands in the
// spec package as committed artifacts: openapi.json and openapi.yaml.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/wheelsdown/spivot-server/internal/server/api"
)

// jsonEncoder returns an encoder producing the committed artifact
// style: two-space indentation, no HTML escaping, trailing newline.
func jsonEncoder(w io.Writer) *json.Encoder {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	return enc
}

func main() {
	out := flag.String("out", "spec", "directory to write openapi.json and openapi.yaml into")
	missingDocs := flag.String("missing-docs", "warn",
		"policy for contract fields without doc comments: warn (summary) or error (list every field and fail)")
	flag.Parse()

	// Validate the policy up front, not only when there is something
	// to report — otherwise a typo'd value would pass silently on a
	// fully documented tree and only explode when the first
	// undocumented field appears.
	if *missingDocs != "warn" && *missingDocs != "error" {
		fmt.Fprintf(os.Stderr, "openapigen: unknown -missing-docs policy %q (want warn or error)\n", *missingDocs)
		os.Exit(1)
	}

	// The default is relative because go:generate runs this command
	// from the api package directory. Refuse to scatter artifacts
	// anywhere that isn't the spec package.
	if _, err := os.Stat(filepath.Join(*out, "spec.go")); err != nil {
		fmt.Fprintf(os.Stderr, "openapigen: refusing to write to %q: not the spec package (no spec.go): %v\n", *out, err)
		os.Exit(1)
	}

	res, err := generate()
	if err != nil {
		fmt.Fprintf(os.Stderr, "openapigen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(*out, "openapi.json"), res.JSON, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "openapigen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(*out, "openapi.yaml"), res.YAML, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "openapigen: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("openapigen: wrote %s and %s (%d routes)\n",
		filepath.Join(*out, "openapi.json"), filepath.Join(*out, "openapi.yaml"), len(api.Routes()))

	// The missing-doc rule (issue #43 phase 2, warn level; the
	// capstone flips CI to error once the backfill lands). The
	// artifacts are written either way — an undocumented field is a
	// documentation gap, not a broken contract.
	if len(res.Undocumented) > 0 {
		if *missingDocs == "error" {
			for _, field := range res.Undocumented {
				fmt.Fprintf(os.Stderr, "  undocumented: %s\n", field)
			}
			fmt.Fprintf(os.Stderr, "openapigen: error: %d contract fields lack doc comments\n", len(res.Undocumented))
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "openapigen: warning: %d contract fields lack doc comments (-missing-docs=error lists them; issue #43 backfill)\n",
			len(res.Undocumented))
	}
}

// result carries the generated artifacts plus the missing-doc
// worklist main reports at the configured policy level.
type result struct {
	JSON         []byte
	YAML         []byte
	Undocumented []string
}

func generate() (result, error) {
	routes := api.Routes()
	// The api package owns the table invariants; refuse to project
	// a spec from a table the server itself would refuse to serve.
	if err := api.ValidateRoutes(routes); err != nil {
		return result{}, err
	}

	docs, err := loadDocIndex(".", collectRoutePackages(routes))
	if err != nil {
		return result{}, err
	}

	builder := newSchemaBuilder(docs)
	doc, err := buildDocument(routes, builder)
	if err != nil {
		return result{}, err
	}

	var buf strings.Builder
	enc := jsonEncoder(&buf)
	if err := enc.Encode(doc); err != nil {
		return result{}, fmt.Errorf("marshal document: %w", err)
	}
	jsonBytes := []byte(buf.String())

	yamlBody, err := yamlFromJSON(jsonBytes)
	if err != nil {
		return result{}, fmt.Errorf("convert to yaml: %w", err)
	}
	return result{
		JSON:         jsonBytes,
		YAML:         append([]byte("# Code generated by internal/tools/openapigen. DO NOT EDIT.\n"), yamlBody...),
		Undocumented: builder.undocumented,
	}, nil
}

// collectRoutePackages gathers every package declaring a named struct
// reachable from the route table's contract types, sorted for
// deterministic loading.
func collectRoutePackages(routes []api.Route) []string {
	var roots []reflect.Type
	for _, rt := range routes {
		for _, v := range []any{rt.Request, rt.Response} {
			if v != nil {
				roots = append(roots, reflect.TypeOf(v))
			}
		}
	}
	pkgs := collectPackagePaths(roots)
	sort.Strings(pkgs)
	return pkgs
}

func buildDocument(routes []api.Route, schemas *schemaBuilder) (*omap, error) {
	paths := newOmap()
	for _, rt := range routes {
		op, err := buildOperation(rt, schemas)
		if err != nil {
			return nil, fmt.Errorf("route %s %s: %w", rt.Method, rt.Path, err)
		}
		item, _ := paths.get(rt.Path)
		if item == nil {
			item = newOmap()
			paths.set(rt.Path, item)
		}
		item.(*omap).set(strings.ToLower(rt.Method), op)
	}

	info := newOmap().
		set("title", "Spivot Server API").
		set("version", api.ContractVersion).
		set("description", "Native HTTP API of Spivot Server, the Go backend for the "+
			"Spivot iOS app, speaking the OpenCaravan protocol.\n\n"+
			"This document is generated from the Go source (route table + contract "+
			"structs) by internal/tools/openapigen; it cannot drift from the "+
			"implementation. The `x-spivot-auth` extension on each operation records "+
			"the enforced authentication posture, derived from the same table that "+
			"wires the middleware.")

	tags := make([]any, 0, len(api.RouteTags()))
	for _, tag := range api.RouteTags() {
		tags = append(tags, newOmap().set("name", tag.Name).set("description", tag.Description))
	}

	securitySchemes := newOmap().
		set("mutualTLS", newOmap().
			set("type", "mutualTLS").
			set("description", "An enrolled client-app certificate, presented directly "+
				"via mTLS or forwarded by a trusted edge proxy. Obtained from "+
				"`clientAppEnroll`.")).
		set("macaroonSession", newOmap().
			set("type", "http").
			set("scheme", "macaroon").
			set("description", "`Authorization: Macaroon <token>` — a base64url session "+
				"macaroon minted by `sessionCreate`, carrying user/client-app/action "+
				"caveats and, for journey-scoped operations, a journey caveat that "+
				"must match the journey named in the request path."))

	doc := newOmap().
		set("openapi", "3.1.0").
		set("info", info).
		set("tags", tags).
		set("paths", paths).
		set("components", newOmap().
			set("securitySchemes", securitySchemes).
			set("schemas", schemas.schemas))
	return doc, nil
}

func buildOperation(rt api.Route, schemas *schemaBuilder) (*omap, error) {
	op := newOmap().
		set("operationId", rt.OperationID).
		set("summary", rt.Summary).
		set("tags", rt.Tags)

	if params := api.PathParams(rt.Path); len(params) > 0 {
		list := make([]any, 0, len(params))
		for _, p := range params {
			param := newOmap().
				set("name", p).
				set("in", "path").
				set("required", true).
				set("schema", newOmap().set("type", "string"))
			if rt.Auth == api.AuthSession && p == rt.JourneyPathParam {
				param.set("description", "Journey identifier; must match the session macaroon's journey caveat.")
			}
			list = append(list, param)
		}
		op.set("parameters", list)
	}

	if rt.Request != nil {
		schema, err := schemas.schemaFor(reflect.TypeOf(rt.Request))
		if err != nil {
			return nil, fmt.Errorf("request schema: %w", err)
		}
		op.set("requestBody", newOmap().
			set("required", !rt.RequestOptional).
			set("content", newOmap().
				set("application/json", newOmap().set("schema", schema))))
	}

	responses := newOmap()
	for _, status := range rt.SuccessStatuses {
		response := newOmap().set("description", http.StatusText(status))
		if rt.Response != nil {
			schema, err := schemas.schemaFor(reflect.TypeOf(rt.Response))
			if err != nil {
				return nil, fmt.Errorf("response schema: %w", err)
			}
			response.set("content", newOmap().
				set("application/json", newOmap().set("schema", schema)))
		}
		responses.set(fmt.Sprintf("%d", status), response)
	}
	op.set("responses", responses)

	auth := newOmap().set("posture", string(rt.Auth))
	switch rt.Auth {
	case api.AuthIdentity:
		op.set("security", []any{newOmap().set("mutualTLS", []any{})})
	case api.AuthSession:
		op.set("security", []any{newOmap().set("macaroonSession", []any{})})
		auth.set("session_action", string(rt.SessionAction))
		auth.set("journey_path_param", rt.JourneyPathParam)
	}
	op.set("x-spivot-auth", auth)
	return op, nil
}
