// Command openapigen projects the native API's OpenAPI contract from
// the Go source. The api package's route table ([api.Routes]) supplies
// the paths and per-operation auth metadata; the contract structs the
// table references supply components/schemas, with each field's GoDoc
// comment carried over as its property description. Because the spec
// is generated, it cannot drift from the code — the structs and the
// route table ARE the contract (issue #43).
//
// Run via `just generate` (a go:generate directive in the api package
// invokes it with the package directory as cwd). Output lands in the
// spec package as committed artifacts: openapi.json and openapi.yaml.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/wheelsdown/spivot-server/internal/server/api"
)

// jsonEncoder returns an encoder producing the committed artifact
// style: two-space indentation, no HTML escaping, trailing newline.
func jsonEncoder(w io.Writer) *json.Encoder {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	return enc
}

// specVersion is the advertised info.version of the generated
// document. Deliberately decoupled from the build version so the
// committed artifact does not churn every release: bump it when the
// documented contract changes shape, freeze it at 1.0.0 when the
// capstone phase of issue #43 declares the surface stable.
const specVersion = "0.1.0"

// tagDescriptions gives every route-table tag its rendered
// description, in sidebar display order. buildDocument fails when a
// route names a tag missing here, so a new domain cluster cannot
// ship an undescribed sidebar section.
var tagDescriptions = []struct {
	name        string
	description string
}{
	{"System", "Service identity, health, readiness, and build metadata."},
	{"Identity", "Client-app enrollment, session macaroons, and server-registration invites."},
	{"Journeys", "Journey lifecycle and telemetry."},
	{"Journey Vehicles", "Journey-scoped vehicle bundles, ACL revisions, and driver attestations."},
	{"Garages", "Account-scoped garage containers: revisions, ownership, vehicles, and invites."},
}

func main() {
	out := flag.String("out", "spec", "directory to write openapi.json and openapi.yaml into")
	flag.Parse()

	// The default is relative because go:generate runs this command
	// from the api package directory. Refuse to scatter artifacts
	// anywhere that isn't the spec package.
	if _, err := os.Stat(filepath.Join(*out, "spec.go")); err != nil {
		fmt.Fprintf(os.Stderr, "openapigen: refusing to write to %q: not the spec package (no spec.go): %v\n", *out, err)
		os.Exit(1)
	}

	jsonBytes, yamlBytes, err := generate()
	if err != nil {
		fmt.Fprintf(os.Stderr, "openapigen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(*out, "openapi.json"), jsonBytes, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "openapigen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(*out, "openapi.yaml"), yamlBytes, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "openapigen: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("openapigen: wrote %s and %s (%d routes)\n",
		filepath.Join(*out, "openapi.json"), filepath.Join(*out, "openapi.yaml"), len(api.Routes()))
}

func generate() (jsonBytes, yamlBytes []byte, err error) {
	routes := api.Routes()
	if err := validateRoutes(routes); err != nil {
		return nil, nil, err
	}

	docs, err := loadDocIndex(".", collectRoutePackages(routes))
	if err != nil {
		return nil, nil, err
	}

	doc, err := buildDocument(routes, newSchemaBuilder(docs))
	if err != nil {
		return nil, nil, err
	}

	var buf strings.Builder
	enc := jsonEncoder(&buf)
	if err := enc.Encode(doc); err != nil {
		return nil, nil, fmt.Errorf("marshal document: %w", err)
	}
	jsonBytes = []byte(buf.String())

	yamlBody, err := yamlFromJSON(jsonBytes)
	if err != nil {
		return nil, nil, fmt.Errorf("convert to yaml: %w", err)
	}
	yamlBytes = append([]byte("# Code generated by internal/tools/openapigen. DO NOT EDIT.\n"), yamlBody...)
	return jsonBytes, yamlBytes, nil
}

// validateRoutes rejects table entries that would generate a
// misleading or colliding spec. These are programmer errors in the
// route table; failing generation is the enforcement.
func validateRoutes(routes []api.Route) error {
	seenOps := map[string]bool{}
	seenPatterns := map[string]bool{}
	for _, rt := range routes {
		id := rt.Method + " " + rt.Path
		switch {
		case rt.OperationID == "":
			return fmt.Errorf("route %s: missing OperationID", id)
		case rt.Summary == "":
			return fmt.Errorf("route %s: missing Summary", id)
		case len(rt.Tags) == 0:
			return fmt.Errorf("route %s: missing Tags", id)
		case len(rt.SuccessStatuses) == 0:
			return fmt.Errorf("route %s: missing SuccessStatuses", id)
		case seenOps[rt.OperationID]:
			return fmt.Errorf("route %s: duplicate OperationID %q", id, rt.OperationID)
		case seenPatterns[id]:
			return fmt.Errorf("route %s: duplicate registration", id)
		}
		seenOps[rt.OperationID] = true
		seenPatterns[id] = true

		known := map[string]bool{}
		for _, tag := range tagDescriptions {
			known[tag.name] = true
		}
		for _, tag := range rt.Tags {
			if !known[tag] {
				return fmt.Errorf("route %s: tag %q has no entry in tagDescriptions", id, tag)
			}
		}

		params := pathParams(rt.Path)
		if rt.Auth == api.AuthSession {
			if rt.SessionAction == "" {
				return fmt.Errorf("route %s: AuthSession without SessionAction", id)
			}
			found := false
			for _, p := range params {
				if p == rt.JourneyPathParam {
					found = true
				}
			}
			if !found {
				return fmt.Errorf("route %s: JourneyPathParam %q not present in path", id, rt.JourneyPathParam)
			}
		} else if rt.SessionAction != "" || rt.JourneyPathParam != "" {
			return fmt.Errorf("route %s: session metadata on non-session route", id)
		}

		if rt.Response == nil && (len(rt.SuccessStatuses) != 1 || rt.SuccessStatuses[0] != http.StatusNoContent) {
			return fmt.Errorf("route %s: nil Response requires exactly one 204 success status", id)
		}
	}
	return nil
}

// collectRoutePackages gathers every package declaring a named struct
// reachable from the route table's contract types, sorted for
// deterministic loading.
func collectRoutePackages(routes []api.Route) []string {
	var roots []reflect.Type
	for _, rt := range routes {
		for _, v := range []any{rt.Request, rt.Response} {
			if v != nil {
				roots = append(roots, reflect.TypeOf(v))
			}
		}
	}
	pkgs := collectPackagePaths(roots)
	sort.Strings(pkgs)
	return pkgs
}

func buildDocument(routes []api.Route, schemas *schemaBuilder) (*omap, error) {
	paths := newOmap()
	for _, rt := range routes {
		op, err := buildOperation(rt, schemas)
		if err != nil {
			return nil, fmt.Errorf("route %s %s: %w", rt.Method, rt.Path, err)
		}
		item, _ := paths.get(rt.Path)
		if item == nil {
			item = newOmap()
			paths.set(rt.Path, item)
		}
		item.(*omap).set(strings.ToLower(rt.Method), op)
	}

	info := newOmap().
		set("title", "Spivot Server API").
		set("version", specVersion).
		set("description", "Native HTTP API of Spivot Server, the Go backend for the "+
			"Spivot iOS app, speaking the OpenCaravan protocol.\n\n"+
			"This document is generated from the Go source (route table + contract "+
			"structs) by internal/tools/openapigen; it cannot drift from the "+
			"implementation. The `x-spivot-auth` extension on each operation records "+
			"the enforced authentication posture, derived from the same table that "+
			"wires the middleware.")

	tags := make([]any, 0, len(tagDescriptions))
	for _, tag := range tagDescriptions {
		tags = append(tags, newOmap().set("name", tag.name).set("description", tag.description))
	}

	securitySchemes := newOmap().
		set("mutualTLS", newOmap().
			set("type", "mutualTLS").
			set("description", "An enrolled client-app certificate, presented directly "+
				"via mTLS or forwarded by a trusted edge proxy. Obtained from "+
				"`clientAppEnroll`.")).
		set("macaroonSession", newOmap().
			set("type", "http").
			set("scheme", "macaroon").
			set("description", "`Authorization: Macaroon <token>` — a base64url session "+
				"macaroon minted by `sessionCreate`, carrying user/client-app/action "+
				"caveats and, for journey-scoped operations, a journey caveat that "+
				"must match the journey named in the request path."))

	doc := newOmap().
		set("openapi", "3.1.0").
		set("info", info).
		set("tags", tags).
		set("paths", paths).
		set("components", newOmap().
			set("securitySchemes", securitySchemes).
			set("schemas", schemas.schemas))
	return doc, nil
}

func buildOperation(rt api.Route, schemas *schemaBuilder) (*omap, error) {
	op := newOmap().
		set("operationId", rt.OperationID).
		set("summary", rt.Summary)
	tags := make([]any, 0, len(rt.Tags))
	for _, tag := range rt.Tags {
		tags = append(tags, tag)
	}
	op.set("tags", tags)

	if params := pathParams(rt.Path); len(params) > 0 {
		list := make([]any, 0, len(params))
		for _, p := range params {
			param := newOmap().
				set("name", p).
				set("in", "path").
				set("required", true).
				set("schema", newOmap().set("type", "string"))
			if rt.Auth == api.AuthSession && p == rt.JourneyPathParam {
				param.set("description", "Journey identifier; must match the session macaroon's journey caveat.")
			}
			list = append(list, param)
		}
		op.set("parameters", list)
	}

	if rt.Request != nil {
		schema, err := schemas.schemaFor(reflect.TypeOf(rt.Request))
		if err != nil {
			return nil, fmt.Errorf("request schema: %w", err)
		}
		op.set("requestBody", newOmap().
			set("required", true).
			set("content", newOmap().
				set("application/json", newOmap().set("schema", schema))))
	}

	responses := newOmap()
	for _, status := range rt.SuccessStatuses {
		response := newOmap().set("description", http.StatusText(status))
		if rt.Response != nil {
			schema, err := schemas.schemaFor(reflect.TypeOf(rt.Response))
			if err != nil {
				return nil, fmt.Errorf("response schema: %w", err)
			}
			response.set("content", newOmap().
				set("application/json", newOmap().set("schema", schema)))
		}
		responses.set(fmt.Sprintf("%d", status), response)
	}
	op.set("responses", responses)

	auth := newOmap().set("posture", string(rt.Auth))
	switch rt.Auth {
	case api.AuthIdentity:
		op.set("security", []any{newOmap().set("mutualTLS", []any{})})
	case api.AuthSession:
		op.set("security", []any{newOmap().set("macaroonSession", []any{})})
		auth.set("session_action", string(rt.SessionAction))
		auth.set("journey_path_param", rt.JourneyPathParam)
	}
	op.set("x-spivot-auth", auth)
	return op, nil
}

// pathParams extracts {wildcard} segment names from a ServeMux
// pattern path, in order of appearance.
func pathParams(path string) []string {
	var params []string
	for _, seg := range strings.Split(path, "/") {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			name := strings.TrimSuffix(strings.TrimPrefix(seg, "{"), "}")
			name = strings.TrimSuffix(name, "...")
			if name != "" && name != "$" {
				params = append(params, name)
			}
		}
	}
	return params
}
